import type { DefaultColorsConfig, SchemeColors } from './types';

const dark = {
	bg: 'var(--ui-surface-900)',
	fg: 'var(--ui-surface-50)',
	base: 'var(--ui-theme-base, var(--ui-surface-200))',
	border: 'color-mix(in srgb, var(--ui-color-fg) 15%, transparent)',
	element: 'color-mix(in srgb, var(--ui-color-fg) 10%, transparent)',
	shadow: 'rgb(0 0 0 / 75%)',
	// bg: 'var(--ui-surface-900)',
	// bgExtra: 'var(--ui-surface-950)',
	// bgMuted: 'var(--ui-surface-700)',
	// fgExtra: 'var(--ui-surface-100)',
	// fgMuted: 'var(--ui-surface-300)',
	// caption: 'color-mix(in srgb, var(--ui-color-fg) 40%, transparent)',
	// captionExtra: 'color-mix(in srgb, var(--ui-color-fg-extra) 60%, transparent)',
	// border: 'color-mix(in srgb, var(--ui-color-fg) 15%, transparent)',
	// borderExtra: 'color-mix(in srgb, var(--ui-color-fg-extra) 25%, transparent)',
	// borderMuted: 'color-mix(in srgb, var(--ui-color-fg) 10%, transparent)',
	// box: 'color-mix(in srgb, var(--ui-color-bg-extra) 75%, transparent)',
	// boxExtra: 'color-mix(in srgb, var(--ui-color-bg-extra) 90%, transparent)',
	// element: 'color-mix(in srgb, var(--ui-color-fg) 10%, transparent)',
	// elementExtra: 'color-mix(in srgb, var(--ui-color-fg) 18%, transparent)',
	// glare: 'color-mix(in srgb, var(--ui-color-fg-extra) 15%, transparent)',
	// emphasis: 'var(--ui-surface-200)',
	// onEmphasis: 'var(--ui-surface-900)',
	// base: 'var(--ui-theme-base, var(--ui-surface-200))',
	// onBase: 'var(--ui-theme-on-base, var(--ui-color-on-emphasis))',
	// shadowXs: '0 1px 3px rgb(0 0 0 / 40%)',
	// shadowSm: '0 2px 6px rgb(0 0 0 / 50%)',
} satisfies SchemeColors;

const light = {
	bg: 'var(--ui-surface-100)',
	fg: 'var(--ui-surface-950)',
	base: 'var(--ui-theme-base, var(--ui-surface-800))',
	border: 'color-mix(in srgb, var(--ui-color-fg) 15%, transparent)',
	element: 'color-mix(in srgb, var(--ui-color-fg) 8%, transparent)',
	shadow: 'rgb(0 0 0 / 25%)',
	// bgExtra: 'var(--ui-surface-50)',
	// bgMuted: 'var(--ui-surface-300)',
	// fgExtra: 'var(--ui-surface-900)',
	// fgMuted: 'var(--ui-surface-700)',
	// caption: 'color-mix(in srgb, var(--ui-color-fg) 40%, transparent)',
	// captionExtra: 'color-mix(in srgb, var(--ui-color-fg-extra) 60%, transparent)',
	// border: 'color-mix(in srgb, var(--ui-color-fg) 15%, transparent)',
	// borderExtra: 'color-mix(in srgb, var(--ui-color-fg-extra) 25%, transparent)',
	// borderMuted: 'color-mix(in srgb, var(--ui-color-fg) 10%, transparent)',
	// box: 'color-mix(in srgb, var(--ui-color-bg-extra) 85%, transparent)',
	// boxExtra: 'color-mix(in srgb, var(--ui-color-bg-extra) 100%, transparent)',
	// element: 'color-mix(in srgb, var(--ui-color-fg) 8%, transparent)',
	// elementExtra: 'color-mix(in srgb, var(--ui-color-fg) 14%, transparent)',
	// glare: 'color-mix(in srgb, var(--ui-color-fg-extra) 30%, transparent)',
	// emphasis: 'var(--ui-surface-800)',
	// onEmphasis: 'var(--ui-surface-50)',
	// base: 'var(--ui-theme-base, var(--ui-surface-800))',
	// onBase: 'var(--ui-theme-on-base, var(--ui-color-on-emphasis))',
	// shadowXs: '0 1px 2px rgb(0 0 0 / 12%)',
	// shadowSm: '0 2px 4px rgb(0 0 0 / 10%)',
} satisfies SchemeColors;

export const defaultColorsConfig = {
	dark,
	light,
	black: '#000000',
	white: '#ffffff',
} satisfies DefaultColorsConfig;
