export const uiEasing = {
	linear: 'linear',
	ease: 'ease',
	easeIn: 'easeIn',
	easeOut: 'easeOut',
	sine: 'sine',
	sineIn: 'sineIn',
	sineOut: 'sineOut',
	quadratic: 'quadratic',
	quadraticIn: 'quadraticIn',
	quadraticOut: 'quadraticOut',
	cubic: 'cubic',
	cubicIn: 'cubicIn',
	cubicOut: 'cubicOut',
	quartic: 'quartic',
	quarticIn: 'quarticIn',
	quarticOut: 'quarticOut',
	quintic: 'quintic',
	quinticIn: 'quinticIn',
	quinticOut: 'quinticOut',
	exponential: 'exponential',
	exponentialIn: 'exponentialIn',
	exponentialOut: 'exponentialOut',
	circular: 'circular',
	circularIn: 'circularIn',
	circularOut: 'circularOut',
	backward: 'backward',
	backwardIn: 'backwardIn',
	backwardOut: 'backwardOut',
} as const;

export type UiEasing = (typeof uiEasing)[keyof typeof uiEasing];
